--- Database Exploration --
===================================================================================
--- Explore All Objects in the Database
--- Explore All Columns in the Database

SELECT * FROM information_schema.TABLES 

SELECT * FROM information_schema.COLUMNS
WHERE TABLE_NAME = 'dim_customers'




  
--- Dimensions Exploration --
===================================================================================
--- Explore All Countries our customers come from
--- Explore All Categories "The major Divisions"

SELECT DISTINCT country FROM gold.dim_customers

SELECT DISTINCT category, subcategory, product_name
FROM gold.dim_products
ORDER BY 1, 2, 3



--- Date Exploration --
===================================================================================
--- Finding the date of the first and last order
--- How many years of sales are available
--- Finding the youngest and the oldest customer

SELECT 
MIN(order_date) AS oldest_birthdate,
MAX(order_date) AS youngest_birthdate,
DATEDIFF(month, MIN(order_date), MAX(order_date)) AS order_range_months
FROM gold.fact_sales


SELECT 
MIN(birth_date) AS oldest_birthdate,
DATEDIFF(year, MIN(birth_date), GETDATE()) AS oldest_age,
MAX(birth_date) AS youngest_birthdate,
DATEDIFF(year, MAX(birth_date), GETDATE()) AS youngest_age
FROM gold.dim_customers




--- Measures Exploration --
===================================================================================
--- Find the Total Sales
--- Find how many items are sold
--- Find the average selling price
--- Find the Total number of Orders
--- Find the Total number of Products
--- Find the Total number of Customers
--- Find the Total number of Customers that has placed an Order


SELECT 'Total Sales' AS measure_name, SUM(sales_amount) AS measure_value
FROM gold.fact_sales
UNION ALL
SELECT 'Total Quantity', SUM(quantity)
FROM gold.fact_sales
UNION ALL
SELECT 'Average Price' , AVG(price)
FROM gold.fact_sales
UNION ALL
SELECT 'Total Num. Orders', COUNT(DISTINCT order_number)
FROM gold.fact_sales
UNION ALL
SELECT 'Total Num. Products', COUNT(*)
FROM gold.dim_products
UNION ALL
SELECT 'Total Num. Customers', COUNT(*)
FROM gold.dim_customers




--- Magnitude Analysis --
===================================================================================
--- Find total customers by countries - Find total customers by gender
--- Find total products by category
--- What is the average costs in each category?
--- What is the total revenue generated for each category?
--- Find total revenue is generated by each customer
--- What is the distribution of sold items across countries?


SELECT country, COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC


SELECT gender, COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC


SELECT category, COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC


SELECT category, AVG(cost) AS avg_costs
FROM gold.dim_products
GROUP BY category
ORDER BY avg_costs DESC


SELECT p.category,
       SUM(f.sales_amount) total_revenue
FROM gold.fact_sales F 
LEFT JOIN gold.dim_products p 
ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC


SELECT c.customer_key,
       c.firstname,
       c.lastname,
       SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f 
LEFT JOIN gold.dim_customers c 
ON c.customer_key = f.customer_key
GROUP BY c.customer_key, c.firstname, c.lastname
ORDER BY total_revenue DESC


SELECT c.country,
       SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f 
LEFT JOIN gold.dim_customers c 
ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC





--- Ranking Analysis --
===================================================================================
--- Which 5 Products generate the highest revenue
--- What are the 5 worst-performing products in terms of sales?
--- Find the Top-10 customers who have generated the highest revenue
--- The 3 customers with the fewest orders placed


SELECT
       p.product_name,
       SUM(f.sales_amount) total_revenue
FROM gold.fact_sales F 
LEFT JOIN gold.dim_products p 
ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY total_revenue DESC
LIMIT 5



SELECT
       p.product_name,
       SUM(f.sales_amount) total_revenue
FROM gold.fact_sales F 
LEFT JOIN gold.dim_products p 
ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY total_revenue
LIMIT 5


SELECT c.customer_key,
       c.firstname,
       c.lastname,
       SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f 
LEFT JOIN gold.dim_customers c 
ON c.customer_key = f.customer_key
GROUP BY c.customer_key, c.firstname, c.lastname
ORDER BY total_revenue DESC
LIMIT 10


SELECT c.customer_key,
       c.firstname,
       c.lastname,
       COUNT(DISTINCT order_number) AS total_orders
FROM gold.fact_sales f 
LEFT JOIN gold.dim_customers c 
ON c.customer_key = f.customer_key
GROUP BY c.customer_key, c.firstname, c.lastname
ORDER BY total_orders
LIMIT 3


















